docs: update

diff --git a/drop b/drop
--- a/drop
+++ b/drop
@@ -11,6 +11,10 @@ err() {
     exit 1
 }
 
+war() {
+    printf '\033[33m->\033[m %s\n' "$*"
+}
+
 jl() {
 	printf '\n'
 }
@@ -215,7 +219,30 @@ tmpfilesorg(){
 	fi
 }
 
+onlyfilescom(){
+	[ $2 ] || err no input files.
+	if [ "$3" = --expire ]; then
+		curl -F "file=@$2" -F "expire=$4" https://tmpfiles.org/api/v1/upload
+	elif [ "$2" = --help ]; then
+		log drop onlyfiles.com \<file\>
+		log upload normal file to onlyfiles.com
+		jl
+		log drop onlyfiles.com \<file\> --expire \<seconds\>
+		log upload file to onlyfiles.com with a expire time
+		log 60s - 172800s
+		log default: 86400s
+		jl
+		log drop onlyfiles.com --help
+		log shows help message
+	else
+		curl -F "file=@$2" -F "expire=0" https://tmpfiles.org/api/v1/upload
+	fi
+}
+
 main() {
+	[ $(command -v nc) ] || war "nc" not found.
+	[ $(command -v curl) ] || err "curl" not found.
+
 	if [ "$1" = "temp.sh" ]; then
 		tempsh $1 $2 $3 $4
 	elif [ "$1" = "0x0.st" ]; then
@@ -232,8 +259,9 @@ main() {
 		tmpfilelink $1 $2 $3 $4
 	elif [ "$1" = "tmpfiles.org" ]; then
 		tmpfilesorg $1 $2 $3 $4
+	elif [ "$1" = "onlyfiles.com" ]; then
+		onlyfilescom $1 $2 $3 $4
 	elif [ "$1" = "termbin" ]; then
-		[ $(command -v nc) ] || err no nc installed.
 		termbin $1 $2 $3 $4
 	elif [ "$1" = --help ]; then
 		log use:
@@ -248,9 +276,10 @@ main() {
 		log  file.io      - limit: 4gib     - expires: 14d
 		log  tmpfile.link - limit: 100mib   - expires: 7d
 		log  tmpfiles.org - limit: 100mib   - expires: 24h
+		log  onlyfile.com - limit: 100mib   - expires: no
 		log  termbin 
 	elif [ "$1" = --version ]; then
-		log drop 0.2-rc2
+		log drop 0.2-rc3
 	else
 		err no input files/filehost service, use --help.
 		
